name: Add labled item PR to the project

on:
  pull_request:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add To GitHub project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/skipishere/projects/1
          github-token: ${{ secrets.PR_TO_GITHUB_PROJECTS }}
          labeled: automagical
          #TODO
