name: Status changed
on:
  issues:
    types:
      - status
  
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
          STATUS: ${{ github.event.state }}
        run: |
          echo The status is $STATUS: $DESCRIPTION
